
/* Drop Tables */

DROP TABLE TAKION78.PORTFOLIO_DETAIL;
DROP TABLE TAKION78.POSITION;
DROP TABLE TAKION78.ACCONT;
DROP TABLE TAKION78.PORTFOLIO_CASHFLOW;
DROP TABLE TAKION78.PORTFOLIO_RETURN;
DROP TABLE TAKION78.PORTFOLIO_RISK;
DROP TABLE TAKION78.PORTFOLIO_RISK_DETAIL;
DROP TABLE TAKION78.PORTFOLIO_SENSITIVITY;
DROP TABLE TAKION78.BASEDATE;
DROP TABLE TAKION78.EMPLOYEE;
DROP TABLE TAKION78.BIZUNIT;
DROP TABLE TAKION78.BOND_INDEX_DETAIL;
DROP TABLE TAKION78.BOND;
DROP TABLE TAKION78.BOND_INDEX;
DROP TABLE TAKION78.COUNTERPARTY;
DROP TABLE TAKION78.ETF_PDF;
DROP TABLE TAKION78.ETF;
DROP TABLE TAKION78.FUTURES;
DROP TABLE TAKION78.FX_CASH;
DROP TABLE TAKION78.IRC_BUCKET_DETAIL;
DROP TABLE TAKION78.INTEREST_RATE;
DROP TABLE TAKION78.IRC_FUNCTION_DETAIL;
DROP TABLE TAKION78.IR_CURVE;
DROP TABLE TAKION78.MACRO_INDEX;
DROP TABLE TAKION78.OPTIONS;
DROP TABLE TAKION78.RISK_FACTOR;
DROP TABLE TAKION78.STOCK_INDEX_DETAIL;
DROP TABLE TAKION78.STOCK;
DROP TABLE TAKION78.STOCK_INDEX;
DROP TABLE TAKION78.SYNTHETIC_DETAIL;
DROP TABLE TAKION78.SYNTHETICS;
DROP TABLE TAKION78.MARKET_VARIABLE;
DROP TABLE TAKION78.PORTFOLIO;
DROP TABLE TAKION78.VAR_GEN_MCD;
DROP TABLE TAKION78.VOL_CURVE;



/* Drop Tablespaces */

DROP TABLESPACE TS_EGN;




/* Create Tablespaces */

CREATE TABLESPACE TS_EGN
 DEFAULT STORAGE(
 )
 NOLOGGING 
 ONLINE 
 PERMANENT 
 SEGMENT SPACE MANAGEMENT MANUAL 
;



/* Create Tables */

CREATE TABLE TAKION78.ACCONT
(
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	ACCOUNT_NAME VARCHAR2(50),
	DEALER_ID VARCHAR2(20),
	TOTAL_LIMIT NUMBER(19,0),
	PRIMARY KEY (ACCOUNT_ID)
);


CREATE TABLE TAKION78.BASEDATE
(
	BSSD VARCHAR2(8) NOT NULL,
	IS_BIZDAY CHAR(1),
	PREV_BIZDAY VARCHAR2(8),
	NEXT_BIZDAY VARCHAR2(8),
	EOM_BIZDAY VARCHAR2(8),
	EOQ_BIZDAY VARCHAR2(8),
	-- END OF SEMI ANNUAL
	EOS_BIZDAY VARCHAR2(8),
	EOY_BIZDAY VARCHAR2(8),
	FISCAL_BIZDAY VARCHAR2(8),
	PRIMARY KEY (BSSD)
);


CREATE TABLE TAKION78.BIZUNIT
(
	ORG_ID VARCHAR2(20) NOT NULL,
	ORG_NAME VARCHAR2(50),
	PARENT_ORG_ID VARCHAR2(20),
	PRIMARY KEY (ORG_ID)
);


CREATE TABLE TAKION78.BOND
(
	BOND_ID VARCHAR2(20) NOT NULL,
	ISSUER_ID VARCHAR2(30),
	FACE_AMT NUMBER(10,0),
	TOTAL_AMT NUMBER(19,0),
	ISSUE_DATE VARCHAR2(8),
	MATURITY_DATE VARCHAR2(8),
	COUPON_RATE NUMBER(10,8),
	INT_TERM VARCHAR2(10),
	COMPOUND_MTD VARCHAR2(10),
	DAYCOUNT_MTD VARCHAR2(10),
	-- DISCOUNT, BULLET, FIXED, FLOATING, FIXED AMORT, FLOAT_AMORT, ...
	BOND_CF_TYPE VARCHAR2(10),
	-- FISRT, SECONDARY
	PRIORITY_CD VARCHAR2(10),
	-- ABS, MBS, CDO,....
	SECURITIZATION_CD VARCHAR2(10),
	CREDIT_RATING_CD VARCHAR2(10),
	CURR_CD VARCHAR2(3),
	PREMIUM_AT_END NUMBER(10,4),
	-- GOV,ILB, BANK, CORP, ABS,...
	BOND_TYPE VARCHAR2(10),
	INIT_INB_INDEX NUMBER(10,4),
	-- ANNUITY, EQUAL, BULLET
	REDEM_MCD VARCHAR2(10),
	AMORT_ST_DATE VARCHAR2(8),
	DEFER_TERM VARCHAR2(10),
	AMORT_CNT NUMBER(10,0),
	AMORT_FREQ NUMBER(10,0),
	AMORT_AMT NUMBER(19,4),
	IS_CP_PREPAY CHAR(1),
	REF_IRC_ID VARCHAR2(20),
	SPREAD_RATE NUMBER(10,4),
	REFIXING_TERM VARCHAR2(10),
	FIRST_COUPON_DATE VARCHAR2(8),
	-- FORWARD, BACKWARD,...
	CP_DATE_GEN VARCHAR2(10),
	REFIXING_SLIDE_NUM NUMBER(10,0),
	CAP_RATE NUMBER(10,4),
	FLOOR_RATE NUMBER(10,4),
	-- CONVERTIBLE, EXCHANGABLE,...
	STOCK_LINKED_TYPE VARCHAR2(10),
	REF_STOCK_ID VARCHAR2(20),
	OPTION_ST_DATE VARCHAR2(8),
	OPTION_ED_DATE VARCHAR2(8),
	STRIKE_PRICE NUMBER(10,4),
	CONVERSION_RATIO NUMBER(10,4),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (BOND_ID)
);


CREATE TABLE TAKION78.BOND_INDEX
(
	BOND_INDEX_ID VARCHAR2(20) NOT NULL,
	BOND_INDEX_NAME VARCHAR2(50),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (BOND_INDEX_ID)
);


CREATE TABLE TAKION78.BOND_INDEX_DETAIL
(
	BOND_INDEX_ID VARCHAR2(20) NOT NULL,
	BOND_ID VARCHAR2(20) NOT NULL
);


CREATE TABLE TAKION78.COUNTERPARTY
(
	COUNTERPARTY_ID VARCHAR2(20) NOT NULL,
	COUNTERPARTY_NAME VARCHAR2(50),
	-- GOV, BANK, SECURITIES, ASSET, INSURER, BROKER, ...
	COUNTERPARTY_TYPE VARCHAR2(10),
	CORP_NO VARCHAR2(13),
	CREDIT_RATING_CD VARCHAR2(10),
	PRIMARY KEY (COUNTERPARTY_ID)
);


CREATE TABLE TAKION78.EMPLOYEE
(
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(50),
	-- ADMIN, MANAGER, DEALER, STAFF,...
	MEMBER_TYPE VARCHAR2(10),
	ORG_ID VARCHAR2(20),
	PRIMARY KEY (MEMBER_ID)
);


CREATE TABLE TAKION78.ETF
(
	ETF_ID VARCHAR2(20) NOT NULL,
	ETF_NAME VARCHAR2(50),
	ISIN_CD VARCHAR2(20),
	BM_ID VARCHAR2(20),
	BM_COEFFICIENT NUMBER(10,4),
	NUM_PER_CU NUMBER(10,0),
	NUM_SHARES NUMBER(10,0),
	TOT_AMT NUMBER(0,0),
	PRIMARY KEY (ETF_ID)
);


-- NUMBER OF HOLDING STOCK FOR 1 CU OF ETF
CREATE TABLE TAKION78.ETF_PDF
(
	ETF_ID VARCHAR2(20) NOT NULL,
	STOCK_ID VARCHAR2(20) NOT NULL,
	NUM_STOCK NUMBER(10,0),
	PRIMARY KEY (ETF_ID, STOCK_ID)
);


CREATE TABLE TAKION78.FUTURES
(
	FUTURES_ID VARCHAR2(20) NOT NULL,
	ISSUE_DATE VARCHAR2(8),
	MATURITY_DATE VARCHAR2(8),
	UNDERLYING_ID VARCHAR2(20),
	NOTIONAL_AMT NUMBER(19,0),
	STRIKE_PRICE NUMBER(10,4),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (FUTURES_ID)
);


CREATE TABLE TAKION78.FX_CASH
(
	FX_ID VARCHAR2(20) NOT NULL,
	FX_NAME VARCHAR2(50),
	TERM_CURR VARCHAR2(3),
	BASE_CURR VARCHAR2(3),
	-- FOR YEN TO KRW, FX RATE IS QUOTED BASED ON 100 YEN.
	-- SCALE_FACTOR IS SET TO 100 TO USE THE QUOTE PRICE WITHOUT ANY CONVERSION.
	SCALE_FACTOR NUMBER(10,4),
	PRIMARY KEY (FX_ID)
);


CREATE TABLE TAKION78.INTEREST_RATE
(
	IR_ID VARCHAR2(20) NOT NULL,
	IR_NAME VARCHAR2(50),
	ISSUE_DATE VARCHAR2(8),
	MATURITY_DATE VARCHAR2(8),
	COMPOUND_MTD VARCHAR2(10),
	DAYCOUNT_MTD VARCHAR2(10),
	INT_TERM VARCHAR2(10),
	COUPON_RATE NUMBER(10,8),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (IR_ID)
);


CREATE TABLE TAKION78.IRC_BUCKET_DETAIL
(
	IRC_ID VARCHAR2(20) NOT NULL,
	IR_ID VARCHAR2(20) NOT NULL,
	PRIMARY KEY (IRC_ID, IR_ID)
);


CREATE TABLE TAKION78.IRC_FUNCTION_DETAIL
(
	IRC_ID VARCHAR2(20) NOT NULL,
	REF_IRC_ID VARCHAR2(20) NOT NULL,
	COEFFICIENT NUMBER(10,4),
	POWER NUMBER(10,4),
	CONSTANT NUMBER(10,4),
	PRIMARY KEY (IRC_ID, REF_IRC_ID)
);


CREATE TABLE TAKION78.IR_CURVE
(
	IRC_ID VARCHAR2(20) NOT NULL,
	IRC_NAME VARCHAR2(50),
	-- SLIDING, EXPECTATION, CONSTANT,...
	FORWARDIND_MTD VARCHAR2(10),
	-- LINEAR, DIS_LINEAR, LOG_LINEAR, EXPONENTIAL, CONSTANT,
	-- BACKWARD_CON, CUBIC_SPLINE
	INTERPOL_MTD VARCHAR2(10),
	-- BUCKET, CURVE FUNCTION_SUM, CURVE_FUNCTION_MUL
	GENERATION_TYPE VARCHAR2(10),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (IRC_ID)
);


CREATE TABLE TAKION78.MACRO_INDEX
(
	MACRO_INDEX_ID VARCHAR2(20) NOT NULL,
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (MACRO_INDEX_ID)
);


CREATE TABLE TAKION78.MARKET_VARIABLE
(
	MV_ID VARCHAR2(20) NOT NULL,
	MV_NAME VARCHAR2(50),
	MV_TYPE VARCHAR2(10),
	IS_TRADABLE CHAR(1),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (MV_ID)
);


CREATE TABLE TAKION78.OPTIONS
(
	OPTION_ID VARCHAR2(20) NOT NULL,
	OPTION_NAME VARCHAR2(50),
	-- INDEX, STOCK, ELW, ...
	OPTION_TYPE VARCHAR2(10),
	IS_CALL CHAR,
	ISSUE_DATE VARCHAR2(8),
	MATURITY_DATE VARCHAR2(8),
	UNDERLYIND_ID VARCHAR2(20),
	STRIKE_PRICE NUMBER(10,4),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (OPTION_ID)
);


CREATE TABLE TAKION78.PORTFOLIO
(
	PORT_ID VARCHAR2(50) NOT NULL,
	PORT_NAME VARCHAR2(50) NOT NULL,
	GROUP_ID VARCHAR2(20),
	PARENT_PORT_ID VARCHAR2(50),
	LEVEL1 VARCHAR2(20),
	LEVEL2 VARCHAR2(20),
	LEVEL3 VARCHAR2(20),
	LEVLE4 VARCHAR2(20),
	LEVEL5 VARCHAR2(20),
	PRIMARY KEY (PORT_ID)
);


CREATE TABLE TAKION78.PORTFOLIO_CASHFLOW
(
	BSSD VARCHAR2(8) NOT NULL,
	PORT_ID VARCHAR2(50) NOT NULL,
	CF_DATE VARCHAR2(8) NOT NULL,
	CF_AMT NUMBER(19,4),
	CF_PRIN_AMT NUMBER(19,4),
	CF_INT_AMT NUMBER(19,4),
	PRIMARY KEY (BSSD, PORT_ID, CF_DATE)
);


CREATE TABLE TAKION78.PORTFOLIO_DETAIL
(
	PORT_ID VARCHAR2(50) NOT NULL,
	POS_ID VARCHAR2(50) NOT NULL,
	PRIMARY KEY (PORT_ID, POS_ID)
);


CREATE TABLE TAKION78.PORTFOLIO_RETURN
(
	BSSD VARCHAR2(8) NOT NULL,
	PORT_ID VARCHAR2(50) NOT NULL,
	BOOK_AMT NUMBER(19,4),
	PRES_VALUE NUMBER(19,4),
	DAILY_RETURN NUMBER(19,4),
	MONTHLY_RETURN NUMBER(19,4),
	QUARTLY_RETURN NUMBER(19,4),
	ANNUAL_RETURN NUMBER(19,4),
	FISCAL_RETURN NUMBER(19,4),
	DELTA_RETURN NUMBER(19,4),
	GAMMA_RETURN NUMBER(19,4),
	VEGA_RETURN NUMBER(19,4),
	THETA_RETURN NUMBER(19,4),
	RHO_RETURN NUMBER(19,4),
	PRIMARY KEY (BSSD, PORT_ID)
);


CREATE TABLE TAKION78.PORTFOLIO_RISK
(
	BSSD VARCHAR2(8) NOT NULL,
	PORT_ID VARCHAR2(50) NOT NULL,
	VAR_GEN_ID VARCHAR2(10) NOT NULL,
	VAR NUMBER(19,4),
	EXPECTED_SHORTFALL NUMBER(19,4),
	EQ_VAR NUMBER(19,4),
	FX_VAR NUMBER(19,4),
	IR_VAR NUMBER(19,4),
	CO_VAR NUMBER(19,4),
	MARGINAL_VAR NUMBER(19,4),
	CONTRIBUTION_VAR NUMBER(19,4),
	PRIMARY KEY (BSSD, PORT_ID, VAR_GEN_ID)
);


CREATE TABLE TAKION78.PORTFOLIO_RISK_DETAIL
(
	BSSD VARCHAR2(8) NOT NULL,
	PORT_ID VARCHAR2(50) NOT NULL,
	-- FOR VAR_TYPE WITH DELTA_NORMAL, DELTA_GAMMA 
	VAR_GEN_ID VARCHAR2(10) NOT NULL,
	RF_ID VARCHAR2(20) NOT NULL,
	DELTA_EQUV NUMBER(19,4),
	GAMMA_EQUV NUMBER(19,4),
	PRIMARY KEY (BSSD, PORT_ID, VAR_GEN_ID, RF_ID)
);


CREATE TABLE TAKION78.PORTFOLIO_SENSITIVITY
(
	BSSD VARCHAR2(8) NOT NULL,
	PORT_ID VARCHAR2(50) NOT NULL,
	BOOK_AMT NUMBER(19,4),
	PRES_VALUE NUMBER(19,4),
	-- WEIGHTED RESIDUAL MATURITY
	WGT_RES_MATURITY NUMBER(19,4),
	ADJ_DURATION NUMBER(19,4),
	MD_DURATION NUMBER(19,4),
	EFFECT_DURATION NUMBER(19,4),
	ADJ_CONVEXITY NUMBER(19,4),
	EFFECT_CONVEXITY NUMBER(19,4),
	PV01 NUMBER(19,4),
	PRIMARY KEY (BSSD, PORT_ID)
);


CREATE TABLE TAKION78.POSITION
(
	POS_ID VARCHAR2(50) NOT NULL,
	POS_NAME VARCHAR2(50),
	PROD_ID VARCHAR2(20),
	DEALER_ID VARCHAR2(20),
	COUNERTPARTY_ID VARCHAR2(20),
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	INIT_TX_DATE VARCHAR2(8),
	LAST_TX_DATE VARCHAR2(8),
	INIT_TX_PRICE NUMBER(19,4),
	INIT_FEE_AMT NUMBER(19,4),
	INIT_TX_AMT NUMBER(19,4),
	HODING_QTY NUMBER(19,4),
	PRIMARY KEY (POS_ID)
);


CREATE TABLE TAKION78.RISK_FACTOR
(
	RF_ID VARCHAR2(20) NOT NULL,
	RF_NAME VARCHAR2(50),
	-- EQ, IR, FX, CO, VO
	RF_TYPE VARCHAR2(10),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (RF_ID)
);


CREATE TABLE TAKION78.STOCK
(
	STOCK_ID VARCHAR2(20) NOT NULL,
	-- NOMARL, PREFERRED, ETF,SPEC, ...
	STOCK_TYPE VARCHAR2(10),
	-- STOCK EXCHANGE IDENDIFIER
	EXCHANGE_ID VARCHAR2(20),
	IS_LISTED CHAR(0),
	NUM_SHARES NUMBER(10,0),
	ISSUER_ID VARCHAR2(30),
	FACE_AMT NUMBER(10,0),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (STOCK_ID)
);


CREATE TABLE TAKION78.STOCK_INDEX
(
	ST_INDEX_ID VARCHAR2(20) NOT NULL,
	ST_INDEX_NAME VARCHAR2(50),
	INDEX_TYPE VARCHAR2(10),
	PRIMARY KEY (ST_INDEX_ID)
);


CREATE TABLE TAKION78.STOCK_INDEX_DETAIL
(
	ST_INDEX_ID VARCHAR2(20) NOT NULL,
	STOCK_ID VARCHAR2(20) NOT NULL,
	INIT_WEIGHT NUMBER(10,4),
	INIT_AMT NUMBER(19,0),
	IS_ACTIVE CHAR(1),
	SOURCE_TABLE VARCHAR2(50),
	USER_NAME VARCHAR2(20),
	LAST_UPDATED TIMESTAMP,
	PRIMARY KEY (ST_INDEX_ID, STOCK_ID)
);


CREATE TABLE TAKION78.SYNTHETICS
(
	SYN_PROD_ID VARCHAR2(20) NOT NULL,
	-- SWAP, SPREAD, USER_DEFINED
	SYNTHETIC_TYPE VARCHAR2(10),
	SYN_PROD_NAME VARCHAR2(50),
	PRIMARY KEY (SYN_PROD_ID)
);


CREATE TABLE TAKION78.SYNTHETIC_DETAIL
(
	SYN_PROD_ID VARCHAR2(20) NOT NULL,
	SUB_PROD_ID VARCHAR2(20) NOT NULL,
	SUB_PROD_NAME VARCHAR2(50),
	WEIGHT NUMBER(0,0),
	PRIMARY KEY (SYN_PROD_ID, SUB_PROD_ID)
);


CREATE TABLE TAKION78.VAR_GEN_MCD
(
	VAR_GEN_ID VARCHAR2(10) NOT NULL,
	-- DELTA_NORMAL, DELTA_GAMMA, HISTORICAL, MC
	VAR_TYPE VARCHAR2(10),
	TIME_HORIZON NUMBER(10),
	PRIMARY KEY (VAR_GEN_ID)
);


CREATE TABLE TAKION78.VOL_CURVE
(
	VOL_CURVE_ID VARCHAR2(20) NOT NULL,
	VOL_CURVE_NAME VARCHAR2(50),
	PRIMARY KEY (VOL_CURVE_ID)
);



/* Create Foreign Keys */

ALTER TABLE TAKION78.POSITION
	ADD FOREIGN KEY (ACCOUNT_ID)
	REFERENCES TAKION78.ACCONT (ACCOUNT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_CASHFLOW
	ADD FOREIGN KEY (CF_DATE)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.PORTFOLIO_CASHFLOW
	ADD FOREIGN KEY (BSSD)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.PORTFOLIO_RETURN
	ADD FOREIGN KEY (BSSD)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK
	ADD FOREIGN KEY (BSSD)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK_DETAIL
	ADD FOREIGN KEY (BSSD)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.PORTFOLIO_SENSITIVITY
	ADD FOREIGN KEY (BSSD)
	REFERENCES TAKION78.BASEDATE (BSSD)
;


ALTER TABLE TAKION78.BIZUNIT
	ADD FOREIGN KEY (PARENT_ORG_ID)
	REFERENCES TAKION78.BIZUNIT (ORG_ID)
;


ALTER TABLE TAKION78.EMPLOYEE
	ADD FOREIGN KEY (ORG_ID)
	REFERENCES TAKION78.BIZUNIT (ORG_ID)
;


ALTER TABLE TAKION78.BOND_INDEX_DETAIL
	ADD FOREIGN KEY (BOND_ID)
	REFERENCES TAKION78.BOND (BOND_ID)
;


ALTER TABLE TAKION78.BOND_INDEX_DETAIL
	ADD FOREIGN KEY (BOND_INDEX_ID)
	REFERENCES TAKION78.BOND_INDEX (BOND_INDEX_ID)
;


ALTER TABLE TAKION78.POSITION
	ADD FOREIGN KEY (COUNERTPARTY_ID)
	REFERENCES TAKION78.COUNTERPARTY (COUNTERPARTY_ID)
;


ALTER TABLE TAKION78.POSITION
	ADD FOREIGN KEY (DEALER_ID)
	REFERENCES TAKION78.EMPLOYEE (MEMBER_ID)
;


ALTER TABLE TAKION78.ETF_PDF
	ADD FOREIGN KEY (ETF_ID)
	REFERENCES TAKION78.ETF (ETF_ID)
;


ALTER TABLE TAKION78.IRC_BUCKET_DETAIL
	ADD FOREIGN KEY (IR_ID)
	REFERENCES TAKION78.INTEREST_RATE (IR_ID)
;


ALTER TABLE TAKION78.IRC_BUCKET_DETAIL
	ADD FOREIGN KEY (IRC_ID)
	REFERENCES TAKION78.IR_CURVE (IRC_ID)
;


ALTER TABLE TAKION78.IRC_FUNCTION_DETAIL
	ADD FOREIGN KEY (REF_IRC_ID)
	REFERENCES TAKION78.IR_CURVE (IRC_ID)
;


ALTER TABLE TAKION78.IRC_FUNCTION_DETAIL
	ADD FOREIGN KEY (IRC_ID)
	REFERENCES TAKION78.IR_CURVE (IRC_ID)
;


ALTER TABLE TAKION78.BOND
	ADD FOREIGN KEY (BOND_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.BOND_INDEX
	ADD FOREIGN KEY (BOND_INDEX_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.ETF
	ADD FOREIGN KEY (ETF_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.FUTURES
	ADD FOREIGN KEY (UNDERLYING_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.FUTURES
	ADD FOREIGN KEY (FUTURES_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.FX_CASH
	ADD FOREIGN KEY (FX_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.INTEREST_RATE
	ADD FOREIGN KEY (IR_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.MACRO_INDEX
	ADD FOREIGN KEY (MACRO_INDEX_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.OPTIONS
	ADD FOREIGN KEY (UNDERLYIND_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.OPTIONS
	ADD FOREIGN KEY (OPTION_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.POSITION
	ADD FOREIGN KEY (PROD_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.RISK_FACTOR
	ADD FOREIGN KEY (RF_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.STOCK
	ADD FOREIGN KEY (STOCK_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.STOCK_INDEX
	ADD FOREIGN KEY (ST_INDEX_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.SYNTHETICS
	ADD FOREIGN KEY (SYN_PROD_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.SYNTHETIC_DETAIL
	ADD FOREIGN KEY (SUB_PROD_ID)
	REFERENCES TAKION78.MARKET_VARIABLE (MV_ID)
;


ALTER TABLE TAKION78.PORTFOLIO
	ADD FOREIGN KEY (PARENT_PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_CASHFLOW
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_DETAIL
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RETURN
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK_DETAIL
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_SENSITIVITY
	ADD FOREIGN KEY (PORT_ID)
	REFERENCES TAKION78.PORTFOLIO (PORT_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_DETAIL
	ADD FOREIGN KEY (POS_ID)
	REFERENCES TAKION78.POSITION (POS_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK_DETAIL
	ADD FOREIGN KEY (RF_ID)
	REFERENCES TAKION78.RISK_FACTOR (RF_ID)
;


ALTER TABLE TAKION78.ETF_PDF
	ADD FOREIGN KEY (STOCK_ID)
	REFERENCES TAKION78.STOCK (STOCK_ID)
;


ALTER TABLE TAKION78.STOCK_INDEX_DETAIL
	ADD FOREIGN KEY (STOCK_ID)
	REFERENCES TAKION78.STOCK (STOCK_ID)
;


ALTER TABLE TAKION78.ETF
	ADD FOREIGN KEY (BM_ID)
	REFERENCES TAKION78.STOCK_INDEX (ST_INDEX_ID)
;


ALTER TABLE TAKION78.STOCK_INDEX_DETAIL
	ADD FOREIGN KEY (ST_INDEX_ID)
	REFERENCES TAKION78.STOCK_INDEX (ST_INDEX_ID)
;


ALTER TABLE TAKION78.SYNTHETIC_DETAIL
	ADD FOREIGN KEY (SYN_PROD_ID)
	REFERENCES TAKION78.SYNTHETICS (SYN_PROD_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK
	ADD FOREIGN KEY (VAR_GEN_ID)
	REFERENCES TAKION78.VAR_GEN_MCD (VAR_GEN_ID)
;


ALTER TABLE TAKION78.PORTFOLIO_RISK_DETAIL
	ADD FOREIGN KEY (VAR_GEN_ID)
	REFERENCES TAKION78.VAR_GEN_MCD (VAR_GEN_ID)
;



/* Comments */

COMMENT ON COLUMN TAKION78.BASEDATE.EOS_BIZDAY IS 'END OF SEMI ANNUAL';
COMMENT ON COLUMN TAKION78.BOND.BOND_CF_TYPE IS 'DISCOUNT, BULLET, FIXED, FLOATING, FIXED AMORT, FLOAT_AMORT, ...';
COMMENT ON COLUMN TAKION78.BOND.PRIORITY_CD IS 'FISRT, SECONDARY';
COMMENT ON COLUMN TAKION78.BOND.SECURITIZATION_CD IS 'ABS, MBS, CDO,....';
COMMENT ON COLUMN TAKION78.BOND.BOND_TYPE IS 'GOV,ILB, BANK, CORP, ABS,...';
COMMENT ON COLUMN TAKION78.BOND.REDEM_MCD IS 'ANNUITY, EQUAL, BULLET';
COMMENT ON COLUMN TAKION78.BOND.CP_DATE_GEN IS 'FORWARD, BACKWARD,...';
COMMENT ON COLUMN TAKION78.BOND.STOCK_LINKED_TYPE IS 'CONVERTIBLE, EXCHANGABLE,...';
COMMENT ON COLUMN TAKION78.COUNTERPARTY.COUNTERPARTY_TYPE IS 'GOV, BANK, SECURITIES, ASSET, INSURER, BROKER, ...';
COMMENT ON COLUMN TAKION78.EMPLOYEE.MEMBER_TYPE IS 'ADMIN, MANAGER, DEALER, STAFF,...';
COMMENT ON TABLE TAKION78.ETF_PDF IS 'NUMBER OF HOLDING STOCK FOR 1 CU OF ETF';
COMMENT ON COLUMN TAKION78.FX_CASH.SCALE_FACTOR IS 'FOR YEN TO KRW, FX RATE IS QUOTED BASED ON 100 YEN.
SCALE_FACTOR IS SET TO 100 TO USE THE QUOTE PRICE WITHOUT ANY CONVERSION.';
COMMENT ON COLUMN TAKION78.IR_CURVE.FORWARDIND_MTD IS 'SLIDING, EXPECTATION, CONSTANT,...';
COMMENT ON COLUMN TAKION78.IR_CURVE.INTERPOL_MTD IS 'LINEAR, DIS_LINEAR, LOG_LINEAR, EXPONENTIAL, CONSTANT,
BACKWARD_CON, CUBIC_SPLINE';
COMMENT ON COLUMN TAKION78.IR_CURVE.GENERATION_TYPE IS 'BUCKET, CURVE FUNCTION_SUM, CURVE_FUNCTION_MUL';
COMMENT ON COLUMN TAKION78.OPTIONS.OPTION_TYPE IS 'INDEX, STOCK, ELW, ...';
COMMENT ON COLUMN TAKION78.PORTFOLIO_RISK_DETAIL.VAR_GEN_ID IS 'FOR VAR_TYPE WITH DELTA_NORMAL, DELTA_GAMMA ';
COMMENT ON COLUMN TAKION78.PORTFOLIO_SENSITIVITY.WGT_RES_MATURITY IS 'WEIGHTED RESIDUAL MATURITY';
COMMENT ON COLUMN TAKION78.RISK_FACTOR.RF_TYPE IS 'EQ, IR, FX, CO, VO';
COMMENT ON COLUMN TAKION78.STOCK.STOCK_TYPE IS 'NOMARL, PREFERRED, ETF,SPEC, ...';
COMMENT ON COLUMN TAKION78.STOCK.EXCHANGE_ID IS 'STOCK EXCHANGE IDENDIFIER';
COMMENT ON COLUMN TAKION78.SYNTHETICS.SYNTHETIC_TYPE IS 'SWAP, SPREAD, USER_DEFINED';
COMMENT ON COLUMN TAKION78.VAR_GEN_MCD.VAR_TYPE IS 'DELTA_NORMAL, DELTA_GAMMA, HISTORICAL, MC';



