package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * AccountMst generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_MST", schema = "TAKION77")
public class AccountMst implements java.io.Serializable {

	private String id;
	private AccountMst accountMst;
	private String name;
	private Set<Position> positions = new HashSet<Position>(0);
	private Set<AccountMst> accountMsts = new HashSet<AccountMst>(0);

	public AccountMst() {
	}

	public AccountMst(String id) {
		this.id = id;
	}

	public AccountMst(String id, AccountMst accountMst, String name, Set<Position> positions,
			Set<AccountMst> accountMsts) {
		this.id = id;
		this.accountMst = accountMst;
		this.name = name;
		this.positions = positions;
		this.accountMsts = accountMsts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	public AccountMst getAccountMst() {
		return this.accountMst;
	}

	public void setAccountMst(AccountMst accountMst) {
		this.accountMst = accountMst;
	}

	@Column(name = "NAME", length = 50)
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountMst")
	public Set<Position> getPositions() {
		return this.positions;
	}

	public void setPositions(Set<Position> positions) {
		this.positions = positions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountMst")
	public Set<AccountMst> getAccountMsts() {
		return this.accountMsts;
	}

	public void setAccountMsts(Set<AccountMst> accountMsts) {
		this.accountMsts = accountMsts;
	}

}
