package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BaseDate generated by hbm2java
 */
@Entity
@Table(name = "BASE_DATE", schema = "TAKION77")
public class BaseDate implements java.io.Serializable {

	private String bssd;
	private String prevBssd;
	private String nextBssd;
	private String eomBssd;
	private Set<PositionHis> positionHises = new HashSet<PositionHis>(0);
	private Set<PortfolioHis> portfolioHises = new HashSet<PortfolioHis>(0);

	public BaseDate() {
	}

	public BaseDate(String bssd) {
		this.bssd = bssd;
	}

	public BaseDate(String bssd, String prevBssd, String nextBssd, String eomBssd, Set<PositionHis> positionHises,
			Set<PortfolioHis> portfolioHises) {
		this.bssd = bssd;
		this.prevBssd = prevBssd;
		this.nextBssd = nextBssd;
		this.eomBssd = eomBssd;
		this.positionHises = positionHises;
		this.portfolioHises = portfolioHises;
	}

	@Id
	@Column(name = "BSSD", unique = true, nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "PREV_BSSD", length = 8)
	@Size(max = 8)
	public String getPrevBssd() {
		return this.prevBssd;
	}

	public void setPrevBssd(String prevBssd) {
		this.prevBssd = prevBssd;
	}

	@Column(name = "NEXT_BSSD", length = 8)
	@Size(max = 8)
	public String getNextBssd() {
		return this.nextBssd;
	}

	public void setNextBssd(String nextBssd) {
		this.nextBssd = nextBssd;
	}

	@Column(name = "EOM_BSSD", length = 8)
	@Size(max = 8)
	public String getEomBssd() {
		return this.eomBssd;
	}

	public void setEomBssd(String eomBssd) {
		this.eomBssd = eomBssd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baseDate")
	public Set<PositionHis> getPositionHises() {
		return this.positionHises;
	}

	public void setPositionHises(Set<PositionHis> positionHises) {
		this.positionHises = positionHises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baseDate")
	public Set<PortfolioHis> getPortfolioHises() {
		return this.portfolioHises;
	}

	public void setPortfolioHises(Set<PortfolioHis> portfolioHises) {
		this.portfolioHises = portfolioHises;
	}

}
