package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * LgdSeg generated by hbm2java
 */
@Entity
@Table(name = "LGD_SEG", schema = "TAKION77")
public class LgdSeg implements java.io.Serializable {

	private String id;
	private String name;
	private String groupId;
	private String rateCd;
	private String collateralCd;
	private BigDecimal lgd;

	public LgdSeg() {
	}

	public LgdSeg(String id) {
		this.id = id;
	}

	public LgdSeg(String id, String name, String groupId, String rateCd, String collateralCd, BigDecimal lgd) {
		this.id = id;
		this.name = name;
		this.groupId = groupId;
		this.rateCd = rateCd;
		this.collateralCd = collateralCd;
		this.lgd = lgd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GROUP_ID", length = 20)
	@Size(max = 20)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "RATE_CD", length = 20)
	@Size(max = 20)
	public String getRateCd() {
		return this.rateCd;
	}

	public void setRateCd(String rateCd) {
		this.rateCd = rateCd;
	}

	@Column(name = "COLLATERAL_CD", length = 20)
	@Size(max = 20)
	public String getCollateralCd() {
		return this.collateralCd;
	}

	public void setCollateralCd(String collateralCd) {
		this.collateralCd = collateralCd;
	}

	@Column(name = "LGD", precision = 10, scale = 8)
	public BigDecimal getLgd() {
		return this.lgd;
	}

	public void setLgd(BigDecimal lgd) {
		this.lgd = lgd;
	}

}
