package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PdSeg generated by hbm2java
 */
@Entity
@Table(name = "PD_SEG", schema = "TAKION77")
public class PdSeg implements java.io.Serializable {

	private String id;
	private String name;
	private String groupId;
	private String rateCd;
	private String indCd;
	private BigDecimal pd;

	public PdSeg() {
	}

	public PdSeg(String id) {
		this.id = id;
	}

	public PdSeg(String id, String name, String groupId, String rateCd, String indCd, BigDecimal pd) {
		this.id = id;
		this.name = name;
		this.groupId = groupId;
		this.rateCd = rateCd;
		this.indCd = indCd;
		this.pd = pd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GROUP_ID", length = 20)
	@Size(max = 20)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "RATE_CD", length = 20)
	@Size(max = 20)
	public String getRateCd() {
		return this.rateCd;
	}

	public void setRateCd(String rateCd) {
		this.rateCd = rateCd;
	}

	@Column(name = "IND_CD", length = 20)
	@Size(max = 20)
	public String getIndCd() {
		return this.indCd;
	}

	public void setIndCd(String indCd) {
		this.indCd = indCd;
	}

	@Column(name = "PD", precision = 10, scale = 8)
	public BigDecimal getPd() {
		return this.pd;
	}

	public void setPd(BigDecimal pd) {
		this.pd = pd;
	}

}
