package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PortfolioLossId generated by hbm2java
 */
@Embeddable
public class PortfolioLossId implements java.io.Serializable {

	private String bssd;
	private String portfolioId;
	private String lossId;

	public PortfolioLossId() {
	}

	public PortfolioLossId(String bssd, String portfolioId, String lossId) {
		this.bssd = bssd;
		this.portfolioId = portfolioId;
		this.lossId = lossId;
	}

	@Column(name = "BSSD", nullable = false, length = 8)
	@NotNull
	@Size(max = 8)
	public String getBssd() {
		return this.bssd;
	}

	public void setBssd(String bssd) {
		this.bssd = bssd;
	}

	@Column(name = "PORTFOLIO_ID", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "LOSS_ID", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getLossId() {
		return this.lossId;
	}

	public void setLossId(String lossId) {
		this.lossId = lossId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortfolioLossId))
			return false;
		PortfolioLossId castOther = (PortfolioLossId) other;

		return ((this.getBssd() == castOther.getBssd()) || (this.getBssd() != null && castOther.getBssd() != null && this
				.getBssd().equals(castOther.getBssd())))
				&& ((this.getPortfolioId() == castOther.getPortfolioId()) || (this.getPortfolioId() != null
						&& castOther.getPortfolioId() != null && this.getPortfolioId().equals(
						castOther.getPortfolioId())))
				&& ((this.getLossId() == castOther.getLossId()) || (this.getLossId() != null
						&& castOther.getLossId() != null && this.getLossId().equals(castOther.getLossId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBssd() == null ? 0 : this.getBssd().hashCode());
		result = 37 * result + (getPortfolioId() == null ? 0 : this.getPortfolioId().hashCode());
		result = 37 * result + (getLossId() == null ? 0 : this.getLossId().hashCode());
		return result;
	}

}
