package org.domain.webtest.entity;

// Generated Mar 26, 2013 10:42:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * PortfolioHis generated by hbm2java
 */
@Entity
@Table(name = "PORTFOLIO_HIS", schema = "TAKION77")
public class PortfolioHis implements java.io.Serializable {

	private PortfolioHisId id;
	private BaseDate baseDate;
	private Portfolio portfolio;
	private BigDecimal portAmt;
	private Set<PortfolioLoss> portfolioLosses = new HashSet<PortfolioLoss>(0);

	public PortfolioHis() {
	}

	public PortfolioHis(PortfolioHisId id, BaseDate baseDate, Portfolio portfolio) {
		this.id = id;
		this.baseDate = baseDate;
		this.portfolio = portfolio;
	}

	public PortfolioHis(PortfolioHisId id, BaseDate baseDate, Portfolio portfolio, BigDecimal portAmt,
			Set<PortfolioLoss> portfolioLosses) {
		this.id = id;
		this.baseDate = baseDate;
		this.portfolio = portfolio;
		this.portAmt = portAmt;
		this.portfolioLosses = portfolioLosses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bssd", column = @Column(name = "BSSD", nullable = false, length = 8)),
			@AttributeOverride(name = "portfolioId", column = @Column(name = "PORTFOLIO_ID", nullable = false, length = 50)) })
	@NotNull
	public PortfolioHisId getId() {
		return this.id;
	}

	public void setId(PortfolioHisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BSSD", nullable = false, insertable = false, updatable = false)
	@NotNull
	public BaseDate getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(BaseDate baseDate) {
		this.baseDate = baseDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PORTFOLIO_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "PORT_AMT", precision = 20)
	public BigDecimal getPortAmt() {
		return this.portAmt;
	}

	public void setPortAmt(BigDecimal portAmt) {
		this.portAmt = portAmt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portfolioHis")
	public Set<PortfolioLoss> getPortfolioLosses() {
		return this.portfolioLosses;
	}

	public void setPortfolioLosses(Set<PortfolioLoss> portfolioLosses) {
		this.portfolioLosses = portfolioLosses;
	}

}
